In [1]:
import tensorflow as tf
import os
import datetime
import tensorflow_datasets as tfds

%load_ext tensorboard

In [2]:
print(tf.__version__)

2.7.0


In [4]:
dataset, info = tfds.load('amazon_us_reviews/Mobile_Electronics_v1_00', with_info=True)
train_dataset = dataset['train']

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0.incompleteSCNLVK/amazon_us_reviews-train.tfrecord


  0%|          | 0/104975 [00:00<?, ? examples/s]

Dataset amazon_us_reviews downloaded and prepared to /root/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0. Subsequent calls will reuse this data.


In [5]:
info

tfds.core.DatasetInfo(
    name='amazon_us_reviews',
    version=0.1.0,
    description='Amazon Customer Reviews (a.k.a. Product Reviews) is one of Amazons iconic products. In a period of over two decades since the first review in 1995, millions of Amazon customers have contributed over a hundred million reviews to express opinions and describe their experiences regarding products on the Amazon.com website. This makes Amazon Customer Reviews a rich source of information for academic researchers in the fields of Natural Language Processing (NLP), Information Retrieval (IR), and Machine Learning (ML), amongst others. Accordingly, we are releasing this data to further research in multiple disciplines related to understanding customer product experiences. Specifically, this dataset was constructed to represent a sample of customer evaluations and opinions, variation in the perception of a product across geographical regions, and promotional intent or bias in reviews.

Over 130+ million cus

In [6]:
len(list(train_dataset))

104975

In [7]:
BUFFER_SIZE = 30000
BATCH_SIZE = 128

In [8]:
train_dataset = train_dataset.shuffle(BUFFER_SIZE, reshuffle_each_iteration = False)

In [9]:
for reviews in train_dataset.take(2):
  print(reviews)

{'data': {'customer_id': <tf.Tensor: shape=(), dtype=string, numpy=b'27235268'>, 'helpful_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'marketplace': <tf.Tensor: shape=(), dtype=string, numpy=b'US'>, 'product_category': <tf.Tensor: shape=(), dtype=string, numpy=b'Mobile_Electronics'>, 'product_id': <tf.Tensor: shape=(), dtype=string, numpy=b'B00AK7NALY'>, 'product_parent': <tf.Tensor: shape=(), dtype=string, numpy=b'778650927'>, 'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'1pc Black Rubber Proof Anti Skid Sticky Pad Dash Non Slip Washable Reusable Auto Car Dashboard Interior Decoration Mat Holder Universal For Automobile SUV Convertible Sedan Coupe Vehicle Jeep'>, 'review_body': <tf.Tensor: shape=(), dtype=string, numpy=b'Will not stick to the dash of either of my vehicles.  Now it is a place for my phone to rest and not vibrate off my desk.'>, 'review_date': <tf.Tensor: shape=(), dtype=string, numpy=b'2014-12-13'>, 'review_headline': <tf.Tensor: shape=(), dtype

In [11]:
for reviews in train_dataset.take(10):
  review_text = reviews['data']
  print(review_text.get('review_body').numpy())
  print(review_text.get('star_rating'))
  print(tf.where(review_text.get('star_rating')>3,1,0).numpy())

b'Will not stick to the dash of either of my vehicles.  Now it is a place for my phone to rest and not vibrate off my desk.'
tf.Tensor(2, shape=(), dtype=int32)
0
b'I have had this case for my Ipod touch 4th generation for about a year and a half. I am just now looking for a new case. I love how it feels, and its easy to slip into my pocket. The downside is that after I droopped a few times, the snaps that hold it together started to break. It still stays on fine, but a foot of a drop will crack the case off. LOVE the price and Love the design. I am considering buying it again. You get what you pay for. If you want a case that you never have to replace go big and pay big for it. If you dont mind changing your case every once in a while this is great!'
tf.Tensor(4, shape=(), dtype=int32)
1
b"many reviews said it feel off easily but i'm yet to see that problem and for a $1.45 theres nothing better. This item also worked better than a $50 product a friend was using. A must buy if you driv